title: ntt
description: Tools to improve testing with TTCN-3
permalink: pretty

exclude:
  - README.md

theme: jekyll-theme-minimal
logo: static/ntt.png
show_downloads: true

  #plugins:
  #- jekyll-readme-index
  #- jekyll-sitemap
  #- jekyll-seo-tag
  #- jekyll-mentions
